### ISSUE TITLE
Is this even maintained?

### ISSUE THREAD

**Issue by onbjerg** [danryan/hal#47]
It seems rather sporadic whether or not the maintainer is available. Maybe adding a contributor would improve the project?

**Comment by danryan** [comment]
Hi! I'll admit I haven't had much, if any, time to work on this lately. But it is still very much on my mind, and I plan on getting back into it very soon. 

For what the future holds, a refactor is necessary to make this more useful. It's worked for my purposes but folks have stated that it's confusing to use and "halfway between a library and an app [see #39]". I'll be putting in time this weekend to start work on Hal 2.0.
